title: Rakesh Malhotra
logo: /assets/img/Other Pic.jpeg
description:
  <p align="center">
  AI Architect in the making
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rakesh-malhotra/â€>/LinkedIn</a> |
  <a href="https://github.com/ramalhot86">GitHub</a>

show_downloads: true
google_analytics:
 <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Working with Qlik India as Senior Architect for Public Secotr Accounts.
  <br>
  </p
theme: jekyll-theme-minimal
